First commit
HSE-JetBrains-department/2022_similar_dev_search_arifkhanov pull request #1
Opened 2022-01-28 12:32 UTC by Sm1Ling

2022-02-04 12:31 UTC, Sm1Ling commented
modified readme

2022-02-04 12:41 UTC, EgorBu requested changes
Let's squash commits & fix comments - and we can merge)

2022-02-04 12:41 UTC, EgorBu commented on README.md
> +> Текущий ридми содержит описание того что предстоит сделать. Автор репозитория Арифханов Азаматхан, БПИ 198
```suggestion
> Здесь содержится описание того, что предстоит сделать за время исполнения проекта. Автор репозитория Арифханов Азаматхан, БПИ 198
```

2022-02-04 12:41 UTC, EgorBu commented on README.md
> +* Практика работы с CLI (Command-line interface) гита
```suggestion
```

2022-02-04 12:41 UTC, EgorBu commented on README.md
> +* Углубленное понимание принципов работы GIT
```suggestion
* Углубленное понимание принципов работы git и использование git для получения желаемой информации из репозиториев
```

2022-02-04 12:41 UTC, EgorBu commented on README.md
> +* Практика работы с утилитами для парсинга репозиториев, извелечения информации о коммитах
```suggestion
```

2022-02-04 12:41 UTC, EgorBu commented on README.md
> +* Составление датасетов для дальнейшей работы с ними
~ тоже самое для enry/tree-sitter как для git'а

2022-02-04 12:41 UTC, EgorBu commented on README.md
> +* [Курочка-Ряба](https://github.com/Sm1Ling/Ryaba)
```suggestion
```

2022-03-04 10:30 UTC, EgorBu approved these changes
LGTM! Let's squash all commits and than merge

2022-04-08 12:11 UTC, EgorBu requested changes
Almost there! Good job

2022-04-08 12:11 UTC, EgorBu commented on git_repo_extract/commits_info.py
> +from dulwich.diff_tree import TreeChange
please fix  order of imports

2022-04-08 12:11 UTC, EgorBu commented on git_repo_extract/commits_info.py
> +        :return [Added, Deleted]
```suggestion
        :return (Added, Deleted)
```

2022-04-08 12:11 UTC, EgorBu commented on git_repo_extract/commits_info.py
> +        mail = name[name.find('<') + 1:-1]
let's use double quotes everywhere

2022-04-08 12:11 UTC, EgorBu commented on git_repo_extract/star_track.py
> +                       per_page: int = 80) -> Any[List[Dict], Dict]:
docstring doesn't match return type

2022-04-08 12:24 UTC, EgorBu approved these changes
Awesome!

2022-04-08 12:24 UTC, merged